channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=24.0
- pip:
  - mlflow==2.10.1
  - cloudpickle==3.0.0
  - numpy==1.26.3
  - tensorflow-macos==2.15.0
  - tensorflow==2.15.0
name: mlflow-env
